
GET http://localhost:3000/lectures HTTP/1.1
###

GET http://localhost:3000/lectures/5cae70cc049ac2195ccafbd4 HTTP/1.1

###

//create 
POST http://localhost:3000/lectures HTTP/1.1
Content-Type: application/json

{
    "data":{
        "course":"Edwin  Couse ejjjjdw",
        "lecture":"lecture lala la lola"
    }
}

###
// error create
POST http://localhost:3000/lectures HTTP/1.1
Content-Type: application/json

####

//delete equivalent to remove in the DB
DELETE http://localhost:3000/lectures/5cae6b588eff611888b53f1c  HTTP/1.1

###
// UPdate information
PUT http://localhost:3000/lectures/5cae6b578eff611888b53f18 HTTP/1.1
Content-Type: application/json

{
    "data":{
        "course":"EdwinCouse df4",
        "lecture":"lecture Massharishosa2"
    }
}
###
GET http://localhost:3000/lectures HTTP/1.1