
GET http://localhost:3000/lectures HTTP/1.1
###

GET http://localhost:3000/lectures/5cabe6021c9d44000025afb3 HTTP/1.1
GET http://localhost:3000/lectures/MWA HTTP/1.1

###

POST http://localhost:3000/lectures HTTP/1.1
Content-Type: application/json

{
    "data":{
        "course":"EdwinCouse",
        "lecture":"lecture lilii"
    }
}

###
POST http://localhost:3000/lectures HTTP/1.1
Content-Type: application/json

####
DELETE http://localhost:3000/lectures/5cae6322baacc0408078c574  HTTP/1.1

###
PUT http://localhost:3000/lectures/5cae66fc1ac3e503fca347c3 HTTP/1.1
Content-Type: application/json

{
    "data":{
        "course":"EdwinCouse",
        "lecture":"lecture Massharishosa"
    }
}